version: '3'

services:
  cached-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cachedapi
    ports:
      - "3000:3000"
    environment:
      - CACHE_URL=valkey:6379
    depends_on:
      - valkey
    restart: unless-stopped

  valkey:
    image: valkey/valkey:8.1.1-alpine
    container_name: cachedapi-valkey
    ports:
      - "6379:6379"
    # No volumes specified
    restart: unless-stopped